name: BrainsaitMaplinc
options:
  bundleIdPrefix: com.brainsait
  deploymentTarget:
    iOS: "17.0"

targets:
  BrainsaitMaplinc:
    type: application
    platform: iOS
    sources:
      - App
      - Models
      - Views
      - ViewModels
      - Services
      - Components
      - Resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.brainsait.maplinc
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Find nearby healthcare facilities in Riyadh"
      INFOPLIST_KEY_CFBundleDisplayName: "Brainsait Maplinc"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
