name: RHDTEDirectory
options:
  bundleIdPrefix: com.brainsait
  deploymentTarget:
    iOS: "17.0"

targets:
  RHDTEDirectory:
    type: application
    platform: iOS
    sources:
      - App
      - Models
      - Views
      - Services
      - Resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.brainsait.rhdte-directory
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Find nearby healthcare facilities"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
